### ISSUE TITLE
Make it as dotnet tool

### ISSUE THREAD

**Issue by szyb** [lechgu/tinyca#1]
I think it is very useful tool. It would be great to have it as a dotnet tool. Just thought.

**Comment by lechgu** [comment]
interesting idea. the standalone version is still a must, because it has to run without the .net installed. Perhaps it will be not hard to refactor so both versions are easily achievable.

**Comment by szyb** [comment]
There is no need to change the code. It will compile and work as is. As to my knowledge the only thing is to add those lines to csproj
```
<PackAsTool>true</PackAsTool>
<ToolCommandName>dotnet-tinyca</ToolCommandName>
<PackageOutputPath>./nupkg</PackageOutputPath>
```
Then `dotnet pack -c Release` and publish in nuget. 
Also it would be good also add version to csproj as it is important to nuget. Default is 1.0.0.0

Note: tool command name dotnet-tinyca is just a proposal. After installation it would be executed as `dotnet tinyca` or `dotnet-tinyca`. It could be just `tinyca` as well (then usage information would be common for standalone version and dotnet tool)

**Comment by lechgu** [comment]
Fixed.
It is possible to run now standalone or install as a tool from the nuget

**Comment by lechgu** [comment]
The code per se does not need to change. But the simplest way to support both scenarios is to have two separate csproj files, one for the standalone, one for the tool.
